version: "3.8"

services:
  calendar:
    build: .
    image: shcalendar:latest
    container_name: shcalendar-service
    user: "0:0"
    restart: unless-stopped
    environment:
      - PORT=8086
      - DB_PATH=/tmp/calendar.db
      - HABITS_FILE=/app/habits.txt
    ports:
      - "8086:8086"
    volumes:
      - shcalendar_data:/tmp
      - ./habits.txt:/app/habits.txt:ro

volumes:
  shcalendar_data:
